import type { EngineOutput } from '../types.js';

export function generatePlan(output: EngineOutput): string {
  const lines: string[] = [];

  lines.push('# TALKING-CLI-OPTIMIZATION.md');
  lines.push('');
  lines.push(`> Generated by talking-cli v0.1.0`);
  lines.push(`> Current score: **${output.totalScore}/100**`);
  lines.push('');
  lines.push('This plan contains concrete fixes based on the audit results.');
  lines.push('Apply them one by one, then re-run `npx talking-cli audit` to verify.');
  lines.push('');

  if (output.h1.verdict !== 'PASS') {
    const raw = output.h1.raw as { lineCount: number; maxLines: number };
    lines.push('## H1 · Reduce SKILL.md line count');
    lines.push('');
    lines.push(`**Problem**: Your SKILL.md is ${raw.lineCount} lines (budget: ${raw.maxLines}).`);
    lines.push('');
    lines.push('**Fix**: ');
    lines.push(`1. Open \`${output.skillDir}SKILL.md\`.`);
    lines.push('2. Identify every section that describes what to do *after* a specific tool call.');
    lines.push('3. Delete those sections from SKILL.md.');
    lines.push('4. Move the guidance into the relevant tool\'s response as a `hints` field.');
    lines.push('5. Re-run `npx talking-cli audit` to verify the line count dropped.');
    lines.push('');
  }

  if (output.h2.verdict !== 'PASS' && output.h2.verdict !== 'NOT_APPLICABLE') {
    const raw = output.h2.raw as { tools: Array<{ name: string; verdict: string }> };
    lines.push('## H2 · Add hint coverage to tools');
    lines.push('');

    const uncovered = raw.tools.filter((t) => t.verdict === 'FAIL');
    const partial = raw.tools.filter((t) => t.verdict === 'PARTIAL');

    if (uncovered.length > 0) {
      lines.push(`**Problem**: ${uncovered.length} tool(s) have zero fixtures and emit no hints.`);
      lines.push('');
      for (const tool of uncovered) {
        lines.push(`### Tool: \`${tool.name}\``);
        lines.push(`1. Create \`${output.skillDir}talking-cli-fixtures/${tool.name}.error.fixture.json\`.`);
        lines.push(`   - Command should trigger an error path for this tool.`);
        lines.push(`   - Expected output must include a non-empty \`hints\` field.`);
        lines.push(`2. Create \`${output.skillDir}talking-cli-fixtures/${tool.name}.empty.fixture.json\`.`);
        lines.push(`   - Command should trigger a zero-result / empty path.`);
        lines.push(`   - Expected output must include a non-empty \`hints\` field.`);
        lines.push('');
      }
    }

    if (partial.length > 0) {
      lines.push(`**Problem**: ${partial.length} tool(s) are missing required scenario coverage.`);
      lines.push('');
      for (const tool of partial) {
        lines.push(`### Tool: \`${tool.name}\``);
        lines.push(`- Check which scenario is missing (error vs empty-result).`);
        lines.push(`- Add the missing fixture in \`${output.skillDir}talking-cli-fixtures/\`.`);
        lines.push('');
      }
    }
  }

  if (output.totalScore === 100) {
    lines.push('## Score: 100/100');
    lines.push('');
    lines.push('Nothing to fix. Your skill is already talking back. Ship it.');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('After applying these changes, run:');
  lines.push('');
  lines.push('```bash');
  lines.push('npx talking-cli audit .');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}
